apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-mcp-deployment
  labels:
    app: weather-mcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-mcp
  template:
    metadata:
      labels:
        app: weather-mcp
    spec:
      containers:
      - name: weather-mcp
        image: acrmcplab.azurecr.io/weather-mcp:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        # Health check 설정
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-mcp-service
spec:
  selector:
    app: weather-mcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
